Add url_tracker.py
PyAr/CDPedia pull request #307
Opened 2020-09-04 21:38 UTC by NicolasSandoval

This script matches if all the URLs in `pag_elegidas.txt` are included in CDPedia.

2020-09-06 16:28 UTC, facundobatista requested changes
Gran arranque!

Antes de hacer un review fino, te paso algunas consideraciones generales. Podemos charlar los distintos puntos (incluso por telegram), sino avisame cuando esté listo para una segunda pasada... Gracias!

1. Tener funciones/métodos privados tiene sentido cuando estás armando una biblioteca, algo que exponés para que otres consuman, entonces está buenísimo mostrar que algunas cosas son "usables" y otras no. Pero en este caso que es un script, todo interno, no hace falta (sólo "ensucia" los nombres). Resumiendo, te diría que hagas todo público.

2. El default para cuando no te pasan algo en la linea de comando, manejalo donde manejás los parámetros de linea de comando. En otras palabras, a `main()` siempre pasale el nombre del archivo (el que haya pasado le usuarie, o el default).

3. Está bueno lo de escribir el resultado de la operación en un archivo. Algunos detalles a este respecto:
    
    3.1. No hace falta que sea en un directorio aparte! Ahorrate todo el manejo de "Pages_out"

    3.2. Hacé que el nombre tenga el "momento". O sea, si lo corro ahora, que se llame `results-20200906-131823.txt`, entonces si lo corro N veces tengo N resultados, y puedo comparar con lo anterior si corregí cosas, etc. No importa que me quede "sucio" el directorio con muchos archivos, los puedo borrar fácil.

    3.3. Me hace ruido que el formato de la linea esté en un lado (l.78) y dependa de los datos que están en otro lado (l.36). Quizás le pasaría los datos separados y no la tupla armada. Pensalo cómo quedaría si la función de escribir estuviese en Track mismo.

4. En el `except` de la linea 46, si hay un problema que no es HTTPError lo estás escondiendo. Hay que manejar eso.

5. Me hace ruido que la función "urls_to_verify" soporte DOS formatos diferentes, ¿por qué es eso?

6. La clase "Track" está buena, pero la usaría para mantener el estado de las cosas que se mantienen en toda la ejecución. O sea, NO la instanciaría por cada URL, porque así no te provee ningún beneficio sobre tener las dos funciones como públicas y ya. La instanciaría una sola vez (y ahí puede abrir el archivo de salida una sola vez) y le iría pasando URL por URL.

En fin, charlemos cualquier duda! Abrazo!

2020-09-07 16:42 UTC, NicolasSandoval commented
> Gran arranque!
> 
> Antes de hacer un review fino, te paso algunas consideraciones generales. Podemos charlar los distintos puntos (incluso por telegram), sino avisame cuando esté listo para una segunda pasada... Gracias!
> 
> 1. Tener funciones/métodos privados tiene sentido cuando estás armando una biblioteca, algo que exponés para que otres consuman, entonces está buenísimo mostrar que algunas cosas son "usables" y otras no. Pero en este caso que es un script, todo interno, no hace falta (sólo "ensucia" los nombres). Resumiendo, te diría que hagas todo público.
> 2. El default para cuando no te pasan algo en la linea de comando, manejalo donde manejás los parámetros de linea de comando. En otras palabras, a `main()` siempre pasale el nombre del archivo (el que haya pasado le usuarie, o el default).
> 3. Está bueno lo de escribir el resultado de la operación en un archivo. Algunos detalles a este respecto:
>    3.1. No hace falta que sea en un directorio aparte! Ahorrate todo el manejo de "Pages_out"
>    3.2. Hacé que el nombre tenga el "momento". O sea, si lo corro ahora, que se llame `results-20200906-131823.txt`, entonces si lo corro N veces tengo N resultados, y puedo comparar con lo anterior si corregí cosas, etc. No importa que me quede "sucio" el directorio con muchos archivos, los puedo borrar fácil.
>    3.3. Me hace ruido que el formato de la linea esté en un lado (l.78) y dependa de los datos que están en otro lado (l.36). Quizás le pasaría los datos separados y no la tupla armada. Pensalo cómo quedaría si la función de escribir estuviese en Track mismo.
> 4. En el `except` de la linea 46, si hay un problema que no es HTTPError lo estás escondiendo. Hay que manejar eso.
> 5. Me hace ruido que la función "urls_to_verify" soporte DOS formatos diferentes, ¿por qué es eso?
> 6. La clase "Track" está buena, pero la usaría para mantener el estado de las cosas que se mantienen en toda la ejecución. O sea, NO la instanciaría por cada URL, porque así no te provee ningún beneficio sobre tener las dos funciones como públicas y ya. La instanciaría una sola vez (y ahí puede abrir el archivo de salida una sola vez) y le iría pasando URL por URL.
> 
> En fin, charlemos cualquier duda! Abrazo!

Genial gracias por el review!, implementando los cambios. Los charlamos por telegram!

2020-09-17 12:06 UTC, facundobatista requested changes
Buenísimo! Ahí anoté algunos detalles, gracias!!

2020-09-17 12:06 UTC, facundobatista commented on utilities/tests/url_tracker.py
> +    urls = list()
Acá hacé `[]` directamente

2020-09-17 12:06 UTC, facundobatista commented on utilities/tests/url_tracker.py
> +    tags = Track()
No me queda claro el nombre aca. Por qué se Track se llama "Track". Y por qué al instanciarlo se pasa a llamar "tags" (que sería otra cosa...)

2020-09-17 12:06 UTC, facundobatista commented on utilities/tests/url_tracker.py
> +        tags.aftermath.write(chr(128126))
???

2020-09-17 12:06 UTC, facundobatista commented on utilities/tests/url_tracker.py
> +    print('Job Done')
Este "job done" sobra acá, porque ya estás manejando los mensajes correctamente en `main`

2020-09-17 12:06 UTC, facundobatista commented on utilities/tests/url_tracker.py
> +def main(file_='pag_elegidas.txt'):
Que el default sea este archivo es algo más "del programa" que "de main". O sea, manejalo abajo en caso de que sys.argv no tenga lo que querés, y que main acá reciba el filename y listo.

2020-09-17 22:37 UTC, NicolasSandoval commented on utilities/tests/url_tracker.py
> +    instant = datetime.datetime.now()
Correcto, cambiando.

2020-09-17 22:38 UTC, NicolasSandoval commented on utilities/tests/url_tracker.py
> +        self.file_name = 'results-{}.txt'.format(self.instant.strftime('%Y%m%d-%f'))
Si, cambiando a Hora, Minutos y segundos.

2020-09-17 22:38 UTC, NicolasSandoval commented on utilities/tests/url_tracker.py
> +        self.aftermath = open(self.file_name, 'w', encoding='utf-8')
Ok, cambiando el nombre por  resultlog.

2020-09-17 22:38 UTC, NicolasSandoval commented on utilities/tests/url_tracker.py
> +    urls = list()
Listo.

2020-09-17 22:38 UTC, NicolasSandoval commented on utilities/tests/url_tracker.py
> +    tags = Track()
Me quedo de otro branch.

2020-09-17 22:38 UTC, NicolasSandoval commented on utilities/tests/url_tracker.py
> +        tags.aftermath.write(chr(128126))
Ups! Se me escapo un space invader.

2020-09-17 22:38 UTC, NicolasSandoval commented on utilities/tests/url_tracker.py
> +    print('Job Done')
Sisi, removiendo.

2020-09-17 22:38 UTC, NicolasSandoval commented on utilities/tests/url_tracker.py
> +def main(file_='pag_elegidas.txt'):
Ahi lo cambie creo que ahi quedo.

2020-09-22 12:59 UTC, facundobatista approved these changes
Buenisimo!!!! Adentro!

2020-09-22 18:01 UTC, merged