From convert to pil
PyAr/CDPedia pull request #308
Opened 2020-09-06 23:47 UTC by laureanoSilva

Closes #304

2020-09-11 17:47 UTC, fzuccolo commented
Probado, funciona bárbaro! Las imágenes se ven bien.

2020-09-17 12:16 UTC, facundobatista requested changes
Buenísimo!!! Ahí anoté algunos detalles, gracias!

2020-09-17 12:16 UTC, facundobatista commented on src/images/scale.py
> +    """
Si el docstring es una sola linea, quedaría todo en la misma linea. También, que sea imperativo, no presente simple. 

Juntando ambos detalles, sería:

`"""Reduce ..."""`

2020-09-17 12:16 UTC, facundobatista commented on src/images/scale.py
> +    logger.info("Success! Resized image saved at %s" % topath)
Que este logging sea en debug, porque van a ser trillón lineas.

También, dejá que la cadena la arme logger, no vos explicitamente. 

Finalmente, el "Success!" está de más porque no informaste antes una intención. Se lo sacaría, y el resto queda bien informativo de lo que pasó.

En conjunto:

`logger.debug("Resized image saved at %s", topath)`

Habiendo dicho eso, también informaría en ese mensaje el "scale_ratio" así queda en el log que la imagen se tocó de esa manera...

2020-09-17 12:16 UTC, facundobatista commented on src/images/scale.py
> +                    logger.warning("Got %d when processing %s", status, frompath)
Yo manejaría todo el error acá y listo. un try/except alrededor de llamar a `scale_image` (que no devolvería nada) -- si terminó bien, tocás `done_now`, si hubo error, logueas en warning. Listo.

2020-09-17 12:16 UTC, facundobatista commented on src/images/scale.py
> +    except IOError:
Sacaría este try/except de acá en favor de algo más genérico como expliqué abajo, que agarre cualquier problema de esta función...

2020-09-23 02:46 UTC, laureanoSilva commented on src/images/scale.py
> +    """
Listo.

2020-09-24 13:43 UTC, laureanoSilva commented on src/images/scale.py
> +    logger.info("Success! Resized image saved at %s" % topath)
Perfecto.

2020-09-24 13:44 UTC, laureanoSilva commented on src/images/scale.py
> +    except IOError:
Esto está bien. No estoy viendo como hacer para capturar el error mas abajo.

2020-09-24 14:23 UTC, laureanoSilva commented on src/images/scale.py
> +                    logger.warning("Got %d when processing %s", status, frompath)
Hecho, al final logueo en exception. Como sugeriste por telegram

2020-09-29 14:56 UTC, facundobatista approved these changes
Fantástico! Aprobado, pero fijate un par de detalles que comenté, antes de que mergees... gracias!!

2020-09-29 14:56 UTC, facundobatista commented on src/images/scale.py
> +                    scale_image(frompath=frompath, topath=topath, scale_factor=scale)
Los nombres son bastante evidentes, podés usarlo posicionalmente y se entiende,. O sea, yo haría `scale_image(frompath, topath, scale)`, qué te parece?

2020-09-29 14:56 UTC, facundobatista commented on src/images/scale.py
> +    return 0
Ya no hace falta devolver nada acá.

2020-09-30 01:56 UTC, laureanoSilva commented on src/images/scale.py
> +                    scale_image(frompath=frompath, topath=topath, scale_factor=scale)
Me parece bien.

2020-09-30 01:56 UTC, laureanoSilva commented on src/images/scale.py
> +    return 0
Joya. no estaba seguro de eso. Gracias.

2020-09-30 02:42 UTC, merged