Update tutorial and include full python docs
PyAr/CDPedia pull request #309
Opened 2020-09-07 00:39 UTC by fzuccolo

#### Details:

- The full official python documentation (including tutorial) will now be included with any release.
- The URL of the documentation tarball must be specified in `languages.yaml` for each language.
- The tarball will be downloaded and saved in the dump (if it doesn't exist) and reused from there when possible.
- The link to the tutorial in CDPedia page footers will work as always, but now all references to doc pages will point to existing local files

2020-09-14 13:32 UTC, facundobatista commented on src/scraping/pydocs.py
> +logger = logging.getLogger('scraping.pydocs')
Acá lo piola es hacer `getLogger(__name__)`, entonces en todos los módulos la llamada queda igual y al mismo tiempo toma el nombre del módulo...

2020-09-14 13:56 UTC, facundobatista requested changes
Buenísimo, gran trabajo! Ahí fuí comentando detalles. Principalmente todo da vueltas alrededor de "la doc tiene que estar" (y no soportar tanto que pueda no estar), ya que de última, más allá del lenguaje que sea la cdpedia, de última se puede meter la info en inglés...

2020-09-14 13:56 UTC, facundobatista commented on src/scraping/pydocs.py
> +    if url is None:
Yo simplificaría esto, porque si acá soportás que la URL no esté, tenés que soportar en el resto del sistema que el archivo no esté (ejemplo, en `web_app.py`).

Entonces, te diría que si la URL no está, esto NO siga. Podrías acceder directamente (no con el `.get`) en `_tarball_info`, por ejemplo.  O acceder con el get pero si es None hacer un `raise ValueError(msg)`...

2020-09-14 13:56 UTC, facundobatista commented on src/scraping/pydocs.py
> +    if not url.endswith('.tar.bz2'):
De nuevo, simplificaría. El Download tiene que bajar lo que le configuró el usuario. Que lo baje y lo grabe.

Si no era un bz2 va a haber una etapa posterior que falle (o no! quizás la etapa posterior soporta otro formato y todo bien).

2020-09-14 13:56 UTC, facundobatista commented on src/scraping/pydocs.py
> +        fh.write(data)
En estos casos está piola usar [esto que copia de un file-like a otro](https://docs.python.org/dev/library/shutil.html#shutil.copyfileobj).

2020-09-14 13:56 UTC, facundobatista commented on src/scraping/pydocs.py
> +    if not exists:
Yo fallaría más a lo bruto :)

2020-09-15 15:46 UTC, fzuccolo commented on src/scraping/pydocs.py
> +logger = logging.getLogger('scraping.pydocs')
Cambiado en e0b3c0e.

2020-09-15 15:46 UTC, fzuccolo commented on src/scraping/pydocs.py
> +    if url is None:
Es cierto. Ahora si no hay URL se produce un KeyError. Cambiado en b85918b y e341c06.

2020-09-15 15:46 UTC, fzuccolo commented on src/scraping/pydocs.py
> +    if not url.endswith('.tar.bz2'):
Sí, era innecesario. Cambiado en b85918b.

2020-09-15 15:46 UTC, fzuccolo commented on src/scraping/pydocs.py
> +        fh.write(data)
Muy bueno, no conocía esa función! Cambiado en c80bed2.

2020-09-15 15:47 UTC, fzuccolo commented on src/scraping/pydocs.py
> +    if not exists:
Borré el `if`, ahora si no está el archivo se produce un `FileNotFoundError`. Cambiado en b85918b.

2020-09-15 15:47 UTC, fzuccolo commented
Hechas las simplificaciones y correcciones, listo para revisar!

2020-09-19 17:47 UTC, fzuccolo commented
Con bzip2 el tarball es de 6648 KB y recomprimido con LZMA queda de 6120 KB, me parece que es muy poca ganancia como para cambiarlo:

```shell
$ ls -s
6648 python-3.8.5-docs-html.tar.bz2
$ bzip2 -d python-3.8.5-docs-html.tar.bz2
$ xz -z python-3.8.5-docs-html.tar
$ ls -s
6120 python-3.8.5-docs-html.tar.xz
```

2020-09-22 20:57 UTC, facundobatista approved these changes
Genial como quedó! Y sí, no tiene sentido sacarlo de `bz2`. Sale como está!

2020-09-22 21:58 UTC, merged