Se reemplazó print por logger
PyAr/CDPedia pull request #316
Opened 2020-10-12 22:19 UTC by iaraAlfaro

Hay que verificar el nivel de severidad, porque hay algunos casos que pareciera que corresponde DEBUG pero por el uso que se le ha dado corresponde INFO. También tengo dudas de las modificaciones que realice en la carpeta utilities.

2020-10-16 23:04 UTC, facundobatista requested changes
Review online :)

2020-10-16 23:04 UTC, facundobatista commented on cdpetron.py
> +                               imag_config[data]['page_limit'])) debug o info?
`#FIXME: debug o info?`

2020-10-16 23:04 UTC, facundobatista commented on cdpetron.py
> +                               imag_config[data]['page_limit'])) debug o info?
debug!

2020-11-30 20:17 UTC, facundobatista approved these changes

2020-11-30 23:34 UTC, NicolasSandoval approved these changes
+1, Looks nice!

2020-12-01 13:54 UTC, merged