Add CSS scraper
PyAr/CDPedia pull request #317
Opened 2020-10-16 22:02 UTC by fzuccolo

Integrate a CSS scraper into the general scraping procedure. As CSS data may be different for each language, scraped content must be saved into each language's dump.

Mechanism steps:

1. While scraping articles, extract raw CSS links from HTML head and save them to file (as soon as found to avoid data loss).
2. After article scraping is done, parse all collected raw links and extract unique CSS module names (wikipedia uses a [modular system][2] for requesting stylesheets)
3. Download the CSS of each module into its own file.
4. Parse all CSS modules for finding links to external resources (icons, backgrounds, etc.) and download them.
5. Combine all available CSS modules into a single stylesheet, retargeting all external URLs to existing local files.
6. On generation step, copy single stylesheet and its resources to the `assets/static` directory of cdpedia image. 

Some ideas were taken from @spiccinini's [preprocess_stylesheets][1] proof of concept.

[1]: https://github.com/PyAr/CDPedia/commit/477bfb6cd83a9da96bb84675644eaa07a8749de4
[2]: https://www.mediawiki.org/wiki/API:Styling_content

Visually the results are OK, I din't found any styling issue. These are some screenshots of the main page in all available languages: [es](https://user-images.githubusercontent.com/61316398/96311721-8138b400-0fe0-11eb-89ea-76ae9ec7cab3.png) [fr](https://user-images.githubusercontent.com/61316398/96311727-84cc3b00-0fe0-11eb-99c0-1dfc5a529595.png) [pt](https://user-images.githubusercontent.com/61316398/96311731-88f85880-0fe0-11eb-99dc-2c4615a7adbc.png) [ay](https://user-images.githubusercontent.com/61316398/96311737-8bf34900-0fe0-11eb-99d6-e946d573087d.png)

2020-10-19 16:14 UTC, fzuccolo commented
LIsto para review!

2020-10-23 22:20 UTC, facundobatista requested changes
Agregué algunas preguntas y detalles. Es muy grande el PR. Charlemos para cortarlo.

2020-10-23 22:20 UTC, facundobatista commented on src/scraping/css.py
> +            self.links = set(line.strip() for line in self._fh)
Acá podés hacer directamente un set comprehension: `{line.strip() for line in self._fh}`

2020-10-23 22:20 UTC, facundobatista commented on src/scraping/css.py
> +            self._fh = open(links_file, 'wt', encoding='utf-8', buffering=1)
¿Por qué el `buffering=1`?

2020-10-23 22:20 UTC, facundobatista commented on src/scraping/css.py
> +        new_links = set(self._findlinks(html)).difference(self.links)
Podés aprovechar la sintaxis de Python para esto: `set(self._findlinks(html)) - self.links`

2020-10-23 22:20 UTC, facundobatista commented on src/scraping/css.py
> +    link_extractor.close()
Tener un recurso instanciado a nivel de módulo pero cerrarle un atributo al llamar una función es muy raro.

Quizás no debería cerrarse nada, o debería instanciarse acá también.

También es raro que al scraper se le pasa algo del link extractor, luego eso se cierra, después se usa el scraper. Es dificil entender el por qué de esa secuencia.

2020-10-23 22:20 UTC, facundobatista commented on src/scraping/css.py
> +    joiner.join(cssdir)
Acá instanciás una clase y le llamás una función. Fin. ¿Vale la pena que _Joiner sea una clase, entonces?

2020-11-27 22:52 UTC, fzuccolo commented
Cierro, se eligió implementar por partes: #321 #324 #334

2020-11-27 23:24 UTC, fzuccolo commented
Cierro: implementado por partes (#321, #324 y #334).

2020-11-27 23:24 UTC, closed without merging