Infra de prueba
PyAr/CDPedia pull request #319
Opened 2020-10-20 16:35 UTC by laureanoSilva

A View was added in /test-infra that from a list of articles (extra-pages.txt) that present certain complexities shows those articles one by one while pressing F5 or clicking on "Next article", in the foother.

closes #130

2020-10-21 14:11 UTC, laureanoSilva commented on src/web/templates/test-infra.html
> +{{ gettext('<a href="%s">próximo artículo</a>') % ('/test-infra') }}
debería agregar esa cadena al archivo .po?

2020-10-21 14:11 UTC, laureanoSilva commented on src/web/web_app.py
> +            with open("extra-pages.txt", 'r') as articles_to_try:
No encontré una forma de parametrizar esto. Entonces, ¿deberíamos documentar la necesidad de que el archivo con artículos "raros" se llame "extra-pages.txt" (o de alguna otra forma que podamos definir)?

2020-10-27 12:47 UTC, facundobatista requested changes
Anoté algo de lo que habíamos hablado, un par de detalles más, y contesté tus preguntas. Gracias!

2020-10-27 12:47 UTC, facundobatista commented on src/web/templates/test-infra.html
> +{{ gettext('<a href="%s">próximo artículo</a>') % ('/test-infra') }}
Nah, esto es para developers nada más. No va a aparecer en las páginas "finales", cierto?

2020-10-27 12:47 UTC, facundobatista commented on src/web/web_app.py
> +            with open("extra-pages.txt", 'r') as articles_to_try:
Yo no lo parametrizaría. Pero tendría ese `extra-pages.txt` ya en disco con un par de artículos. Entonces, no hay chance de confusión.

2020-10-27 12:47 UTC, facundobatista commented on src/web/web_app.py
> +    def on_test_infra(self, request, remaining=[]):
Acordate de sacar el remaining de acá y hacer lo de `itertools.cycle` que hablamos...

2020-10-27 12:47 UTC, facundobatista commented on src/web/web_app.py
> +            with open("extra-pages.txt", 'r') as articles_to_try:
¿No hay que abrir el archivo con `encoding='utf8'`?

2020-10-27 12:47 UTC, facundobatista commented on src/web/web_app.py
> +        except Exception as err:
Qué tipo de problema estás considerando acá que va a suceder?

2020-10-27 22:18 UTC, laureanoSilva commented on src/web/templates/test-infra.html
> +{{ gettext('<a href="%s">próximo artículo</a>') % ('/test-infra') }}
Cierto, queda.

2020-10-27 22:19 UTC, laureanoSilva commented on src/web/web_app.py
> +            with open("extra-pages.txt", 'r') as articles_to_try:
Perfecto. commiteo el extra-pages entonces.

2021-01-19 03:14 UTC, fzuccolo commented
#### Cambios:

Agregado archivo `test_infra.txt` con el siguiente formato:

```ini
[es]
Portal:Portada # Check page looks OK
República_Agentina # Article with 'Argentina' title is shown
# this comment should be ignored
Satélites_de_Saturno

[fr]
Château # Image galleries shouldn't overflow
```

Este archivo se copiará al directorio de assets de web_app solo cuando se cree una CDPedia en modo test.
Es la presencia de este archivo la que determina si el endpoint `test_infra` funciona o devuelve 404.

#### Utilización:

- Crear una CDPedia en modo test
- Visitar `localhost:8000/test_infra`
- Navegar las páginas haciendo click en `🢂` o apretando `F5`

<kbd><img width="500" alt="test_infra_screenshot" src="https://user-images.githubusercontent.com/61316398/104983087-d377df80-59ea-11eb-8188-d296355223d1.PNG"></kbd>

2021-01-23 13:02 UTC, facundobatista requested changes
Bárbaro, gran trabajo! Ahí anoté un detalle a corregir, gracias!

2021-01-23 13:02 UTC, facundobatista commented on src/web/web_app.py
> +        except StopIteration:
Pero si estás haciendo un `cycle()` de las páginas, nunca vas a tener un StopIteration...

2021-01-23 15:31 UTC, fzuccolo commented on src/web/web_app.py
> +        except StopIteration:
Era para el caso de una lista vacía, pero no tiene sentido verificar eso en cada iteración. Mejorado en 7284dfc.

2021-01-28 17:49 UTC, facundobatista approved these changes
Maravilloso, gracias!

2021-01-28 17:49 UTC, merged