CSS Scraper (1/3): Extract CSS links while scraping articles
PyAr/CDPedia pull request #321
Opened 2020-10-24 18:34 UTC by fzuccolo

Extract raw CSS links from each scraped HTML just before the `<head>` is discarded.

2020-10-24 18:51 UTC, fzuccolo commented on src/scraping/scraper.py
> +    extract_css_links.close()
Tengo dudas con esto. Una alternativa a usar `global extract_css_links` es pasar la instancia como parámetro a `fetch`, luego a `save_htmls` y finalmente a `save_htmls` donde efectivamente se usa. ¿Es preferible hacerlo así?

¿Cuál sería una mejor diseño para implementar esto? Por ej. podría ser algo así:

```python
class ArticleScraper:
    def __init__(self, langdir):
        self.extract_css_links = CSSLinkExtractor(langdir)
    
    def get_html(self, url):
        html = ...
        self.extract_css_links(html)
        ...
        return stripped_html
   
    def fetch(self, data_url):
        html = self.get_html(url)
        ...

def main(...):
    ...
    func = ArticleScraper(langdir).fetch
    utiles.pooled_exec(func, data_urls)
```

2020-10-27 13:02 UTC, facundobatista requested changes
Buenísimo, ahí anoté un par de cambios y te contesté tu pregunta (con detalles incluidos). Gracias!

2020-10-27 19:59 UTC, fzuccolo commented on src/scraping/scraper.py
> +    extract_css_links.close()
> instanciá CSSLinkExtractor a nivel de módulo

Perfecto, lo implementé así, con instancia a nivel de módulo.

> yo no lo llamaría `extract_css_links` y no usaría un `__call__`

Es cierto, no tiene sentido que parezca una función: cambié el nombre a `css_link_extractor`, saqué el `__call__` y agregué el método `collect`, quedó mucho más claro.

> no es obvio que "dirname(dest_dir)" sea el lenguaje... no se puede tomar el idioma de la config, por ejemplo?

El lenguaje sí está en la config, pero no el path del dump. `dest_dir` por ej. es `foo/mydump/es/articles/` y la lista de links (y el CSS) va en `foo/mydump/es/css/`. Una alternativa podría ser agregar `config.location = location` en cdpetron, después de:

https://github.com/PyAr/CDPedia/blob/84c7b4c6a5830a64bb1627e59394157293751813/cdpetron.py#L392

y tomar el path que necesita la clase con `config.location.cssdir` (en runtime). O pasarle otro parámetro al `main` del scraper.

2020-10-27 19:59 UTC, fzuccolo commented on cdpetron.py
> +        self.cssdir = os.path.join(self.langdir, config.CSS_DIRNAME)
cdpetron no lo necesita, pero `CSSLinkExtractor` espera que exista por que en ese directorio se crea `css_links.txt`

https://github.com/PyAr/CDPedia/blob/84c7b4c6a5830a64bb1627e59394157293751813/src/scraping/scraper.py#L286-L289

Si descartamos la idea del otro comentario de usar `config.location.cssdir` entonces creo el directorio justo acá.

2020-10-27 20:00 UTC, fzuccolo commented
Gracias por la respuesta detallada! Implementé los cambios, quedan un par de detalles por resolver en los comentarios.

2020-11-03 22:57 UTC, facundobatista approved these changes
Maravilloso! Vayamos ahora por el 2/3 :) -- Gracias!

2020-11-03 23:45 UTC, merged