CSS Scraper (2/3): Download CSS modules and associated resources
PyAr/CDPedia pull request #324
Opened 2020-11-04 15:40 UTC by fzuccolo

#### Mechanism

1. Load the raw CSS links that were extracted while scraping articles.
2. Extract unique CSS module names from those raw urls (wikipedia uses a [modular system][1] for requesting stylesheets).
3. Download the CSS of each module into its own file (this avoids having duplicated CSS rules in different files).
4. Parse all CSS for finding links to external resources (icons, backgrounds, etc.) and download them all.

Part 2/3 for addressing issue #294.

[1]: https://www.mediawiki.org/wiki/API:Styling_content

2020-11-11 12:06 UTC, facundobatista requested changes
Muy bueno! Charlemos sobre un tema de "cuando bajás y cuando scrapeás".

2020-11-11 12:06 UTC, facundobatista commented on src/scraping/css.py
> +                    self._collect_resources_info(fh.read())
Si juntás recursos de los recursos que ya fueron bajados, ¿cuando juntás recursos de los recursos que todavía no se bajaron?

2020-11-11 12:06 UTC, facundobatista commented on src/scraping/css.py
> +            with open(item['filepath'], 'wt', encoding='utf-8') as fh:
(relacionado con lo de arriba) ¿cuando bajás estos que estás guardando acá?

2020-11-11 16:38 UTC, fzuccolo commented on src/scraping/css.py
> +            names = query.get('modules')[0]
Claro! Usada la sugerencia y actualizado el test para contemplar esa situación. c32ac2c

2020-11-11 16:38 UTC, fzuccolo commented on src/scraping/css.py
> +            exists = os.path.isfile(filepath)
Me refiero a la existencia del archivo. Cambio el nombre de la variable a `is_file` (se me pasó la posible confusión con `os.path.exists`).  1760bac

2020-11-11 16:38 UTC, fzuccolo commented on src/scraping/css.py
> +                    self._collect_resources_info(fh.read())
Acá junto enlaces de los recursos (imágenes, íconos, backgrounds, etc.) que necesitan los CSS que ya están en disco.
Luego a medida que se van descargando los CSS faltantes, busco más enlaces antes que el CSS se guarde.

https://github.com/PyAr/CDPedia/blob/b8407409d7a97dcff8764cdef1932f382a4d495d/src/scraping/css.py#L174-L175

2020-11-11 16:38 UTC, fzuccolo commented on src/scraping/css.py
> +            with open(item['filepath'], 'wt', encoding='utf-8') as fh:
Acá estoy guardando un único módulo CSS (luego de haberlo analizado para extraer info de los recursos que necesita, que se bajan aparte)

2020-11-11 16:39 UTC, fzuccolo commented
Hechas las correcciones. 

Respecto a *bajar/scrapear*, otra opción es: descargar *todo* el CSS primero y buscar los enlaces a otros recursos después (simplifica un poco el código pero agrega lecturas de disco innecesarias).

2020-11-20 19:35 UTC, fzuccolo commented
Mejorada la documentación de acuerdo a lo charlado en la última reunión.
Listo para re-review.

2020-11-26 00:37 UTC, facundobatista approved these changes
Adentro! Gracias!

2020-11-26 00:38 UTC, merged