Description paragraph is taken from first p tag inside teh mw_parser_…
PyAr/CDPedia pull request #338
Opened 2020-12-01 05:54 UTC by marian-vignau

#314 …output's div

2020-12-01 14:02 UTC, facundobatista requested changes
Un par de comentarios simples. Por otro lado, faltaría algún test de esto, no? Al menos el caso de éxito simple.

Gracias!!

2020-12-01 14:02 UTC, facundobatista commented on src/preprocessing/preprocessors.py
> +        node = None
Me hace ruido usar "node" para saber si tenemos un texto o no, porque es muy genérico de explorar la "sopa".

Qué te parece si en vez de poner node en None acá, ponés `safe_text = ''`, luego se hace toda la exploración, que tendrá como resultado que `safe_text = base....`, y luego, afuera de esa exploración, grabás la métrica, que quedaría algo como...

```
    if safe_text:
        self.stats['text found'] += 1
    else:
        self.stats['text not found'] += 1
```

2020-12-01 14:02 UTC, facundobatista commented on src/preprocessing/preprocessors.py
> +                    text = text[:self._max_length] + "..."
¿Qué te parece aprovechar este cambiazo y usar acá esto que es sólo un carácter? `…`

2020-12-03 14:26 UTC, fzuccolo commented
Un par de observaciones:

#### 1. Algunas descripciones no se extraen

Por ej. de Argentina o Rosario:

<kbd><img width="269" src="https://user-images.githubusercontent.com/61316398/101026978-4cfc6100-3556-11eb-93c8-1c872b9feaae.png"></kbd>

En Argentina hay un `<p class="algo">` antes del párrafo `<p>...</p>` que nos interesa

<kbd><img width="215" src="https://user-images.githubusercontent.com/61316398/101027087-71583d80-3556-11eb-8ddb-1b90cca47bac.png"></kbd>

Agregando `class_=None` acá capturamos estos casos:

https://github.com/PyAr/CDPedia/blob/2f3aa6e8cd97c320b787a69f2e4e19af00c4a176/src/preprocessing/preprocessors.py#L103 

<img width="276" alt="Screenshot_2020-12-03 Search CDPedia, la Wikipedia offline(1)" src="https://user-images.githubusercontent.com/61316398/101037268-027ce380-355a-11eb-8adc-acdb34cbe668.png">


#### 2. Tokens en resultados

Me parece que los tokens abajo del título en los resultados son redundantes, ya que esas palabras ya están en el título:

<img width="269" src="https://user-images.githubusercontent.com/61316398/101035813-9bf7c580-3559-11eb-8fc8-a60f1c69a580.png">

Podríamos sacarlos borrando esta línea, no sé que te parece:

https://github.com/PyAr/CDPedia/blob/2f3aa6e8cd97c320b787a69f2e4e19af00c4a176/src/web/templates/search.html#L26

2020-12-07 21:16 UTC, facundobatista approved these changes
Buenísimo!!

2020-12-07 21:16 UTC, merged