Mejorar la tokenización de los títulos al generar entradas de índice
PyAr/CDPedia pull request #347
Opened 2020-12-20 07:17 UTC by fzuccolo

### Incluir tokens con símbolos

Agregada la función `tokenize_title` para una mejor extración de tokens.

| Título | Tokens antes  | Tokens ahora |
| ------------- | ------------- | ------------- |
| `AC/DC` | `ac`, `dc` | `ac`, `dc`, `ac/cd` |
| `.com` | `com` | `com`, `.com` |
| `Fahrenheit 9/11` | `Fahrenheit`, `9`, `11` | `fahrenheit`, `9/11`, `9`, `11`, |

Estas nuevas entradas se agregan al índice, permitiendo obtener los resultados esperados cuando se busca `.com` o `AC/DC` (fix #326).

### Mejorar el comportamiento de la función `normalize_words`:

- convertir a minúsculas
- eliminar diacríticos
- mantener caracteres no ASCII para soportar títulos en alfabetos no latinos

Comportamiento con los cambios:

| Raw | Normalized |
| --- | ---------- |
| `FOO` | `foo` |
| `FóÕ` | `foo` |
| `ñandú` | `nandu` |
| `.com` | `.com` |
| `AC/DC` | `ac/dc` |
| `Србија` | `србија` | 
| `замо́к` | `замок` |
| `παϊδάκια` | `παιδακια` |

Con estos cambios, la tokenización funciona correctamente para caracteres no ASCII (fix #346)

| Título | tokens |
| ------------- | ------------- |
| `Jeep Ñandú` | `jeep`, `nandu` | 
| `Número π` | `numero`, `π` |
| `Έλενα Παπαρίζου` | `ελενα`, `παπαριζου` |
| `♥ Heart (álbum)` | `♥`, `heart`, `album` |

Ahora por ej. si el artículo `Número π` está incluído y se busca `π`, se obtiene:

<kbd><img src="https://user-images.githubusercontent.com/61316398/102707263-2dfd0f00-4278-11eb-8af8-6ea5d9f3348b.png" width="500px"></kbd>

### Tests

- más casos de prueba para `test_word_normalization`
- agregado `test_title_tokenization` para verificar la tokenización que queremos lograr

2020-12-28 23:50 UTC, facundobatista requested changes
Gran laburo! Fijate que ahí anoté una mejora de performance que quizás valga la pena...

2020-12-28 23:50 UTC, facundobatista commented on src/armado/sqlite_index.py
> +    txt = ''.join(c.lower() for c in txt if not unicodedata.combining(c))
Esto está buenísimo. Me preocupa sin embargo estar llamando todo el tiempo al combining ese y al lower, por cada una de las letras...

¿Qué te parece cachear? Hice [alguna prueba simple](http://linkode.org/#wHM1N3jLztQwOQnstA4v94) y es casi el doble de rápido acceder al caché que hacer las otras dos operaciones.

Estoy hablando de hacer algo así:

```
>>> def func(letras):
...    for c in letras:
...       try:
...          normalizado = cache[c]
...       except KeyError:
...          normalizado = '' if unicodedata.combining(c) else c.lower()
...          cache[c] = normalizado
...       yield normalizado
... 
>>> len(textolargo)
22186
>>> txt = unicodedata.normalize('NFKD', textolargo)
>>> len(txt)
22656
>>> timeit.timeit("''.join(c.lower() for c in txt if not unicodedata.combining(c))", globals=globals(), number=1000)
3.0688755358569324
>>> cache = {}
>>> timeit.timeit("''.join(func(txt))", globals=globals(), number=1000)
1.665115047013387
```

Claro, el "cache" sería global, a nivel de módulo (no debería crecer mucho, porque no nos cruzamos con taaaaaaantos caracteres distintos).

2020-12-28 23:50 UTC, facundobatista commented on src/armado/cdpindex.py
> +    return list(words)
Necesitamos que `words` sea una lista? Cómo se consume luego?

2020-12-29 15:54 UTC, fzuccolo commented on src/armado/cdpindex.py
> +    return list(words)
Cambiado, no es necesario que sea una lista.

`easy_index` si esperaba una lista, pero no `sqlite_index`:
https://github.com/PyAr/CDPedia/blob/6046011f6e82bf8acfa637c2ef891315d3ba8b53/src/armado/easy_index.py#L188-L191

2020-12-29 15:55 UTC, fzuccolo commented on src/armado/sqlite_index.py
> +    txt = ''.join(c.lower() for c in txt if not unicodedata.combining(c))
Cambiado. Excelente idea y muy buena la prueba!

2021-01-04 19:27 UTC, facundobatista approved these changes
Buenísimo! Gracias!

2021-01-04 19:27 UTC, merged