Mejoras en el envío de redirects al índice
PyAr/CDPedia pull request #351
Opened 2021-01-08 20:28 UTC by facundobatista

Incluyendo:

- filename2words ahora separa tanto por '_' como por ' '; esto es algo que nos mordió en la creación del beta, que generaba los "títulos repetidos".

- filename2words ahora sólo devuelve `words` (antes también devolvía esas words unidas por espacio); entonces `redirs` sólo almacena esas `words`, y se termina armando el título después (a menos que el redirect sea ignorado, por tener sólo palabras repetidas); esto ahorra memoria seguro, y potencialmente procesamiento.

- ahora no mandamos TODOS los redirects al índice usando TODAS sus palabras, sólo lo que no se usó antes.

Un ejemplo de esto último, indicando qué palabras y título tiene el original, y un par de redirects, y mostrando con qué palabras se encontraría (el título queda tal cual!!!); tener en cuenta que el orden es importante, el original va primero y luego los redirects:

| tipo | words | title | -> | words indizadas |
| ---- | ----- | ----- | -- | -------------   |
| original | `['domingo', 'faustino', 'sarmiento']` | Domingo Faustino Sarmiento | -> | `['domingo', 'faustino', 'sarmiento']` |
| redirect | `['domingo', 'escuelita', 'sarmiento']` | Domingo Escuelita Sarmiento | -> | `['escuelita']` |
| redirect | `['domingo', 'sarmiento']` | Domingo Sarmiento | -> | IGNORADO |
| redirect | `['escuelita', 'sarmiento']` | Escuelita Sarmiento | -> | IGNORADO |
| redirect | `['sarmiento', 'faustino']` | Sarmiento, Faustino | -> | IGNORADO |

Los IGNORADO son redirects que NO se terminan indizando, porque si se busca por cualquiera de sus palabras se terminaría encontrando el original o cualquiera de los redirects anteriores.

2021-01-08 22:09 UTC, fzuccolo commented on src/armado/cdpindex.py
> +                    yield redir_only_words, ptje, data
Por ej. si está incluído el artículo `Argentina` (original) y `República Argentina` (redirect), se da esta situación me parece:

- Busco `argentina` -> `Argentina` entre los resultados
- Busco `republica` -> `republica argentina` entre los resultados
- Busco `republica argentina` -> **sin resultados**

2021-01-08 22:49 UTC, facundobatista commented
NEED FIXING! Lo que tenemos que hacer es ignorar los redirects cuya totalidad de palabras ya están incluidas antes, pero si no, no. Y en todos los redirects, indizarlos con todas sus palabras (porque las búsquedas son con AND... en el ejemplo de arriba, si yo buscara "escuelita sarmiento" no me encontraría nada).

2021-01-11 20:35 UTC, marian-vignau requested changes

2021-01-11 20:35 UTC, marian-vignau commented on src/armado/cdpindex.py
> +        redirs[dest].add(frozenset(words))
Se pierde el orden de las palabras en este caso
```
a = ["color", "de", "zanahoria"]
b = ["zanahoria", "de", "color"]
frozenset(a) == frozenset(b)
True
```
Y puede quedar raro que las salidas al usuario queden con las palabras ordenadas al revés.

2021-01-11 20:35 UTC, marian-vignau commented on src/armado/cdpindex.py
> +                    if words in already_indexed_words:
En este caso, el problema es que si ya está indexado, pongamos
```
c = ["domingo", "faustino", "sarmiento"]
d = ["faustino", "sarmiento"]
frozenset(c) == frozenset(d)
False
```
O sea, si el redir contiene las palabras del título u otro redir, lo va a indexar igual.
Acá abajo adjunto un algoritmo que se fija si un título es un subset de otro redir, en cuyo caso no lo agrega, o es un superset, en cuyo caso remueve el redir que estaba antes y agrega el nuevo.


```
       redirs = defaultdict(set)
         subsets = 0
         for line in open(config.LOG_REDIRECTS, "rt", encoding="utf-8"):
             orig, dest = line.strip().split(config.SEPARADOR_COLUMNAS)
 
             # in the original article, the title is missing
             # so we use the words founded in the filename
             # it isn't the optimal solution, but works
             words, title = filename2words(orig)
             if not words:
                 continue
             wordset = set(words)
             # avoid redirects that are included in other redirect's word set
             remove = set()
             for wset in redirs[dest]:
                 if wordset.issubset(set(wset)):
                     subsets += 1
                     wordset = None
                     break
                 elif wordset.issuperset(set(wset)):
                     remove.add(wset)
                     subsets += 1
             if remove:
                 redirs[dest] -= remove
             if wordset:
                 redirs[dest].add(tuple(words))
```

2021-01-11 22:28 UTC, facundobatista commented on src/armado/cdpindex.py
> +                    if words in already_indexed_words:
No queremos guardar los redirects "superset" de otros, y a los otros no.

O sea, si hay dos redirects `["domingo", "faustino", "sarmiento"]` y `["faustino", "sarmiento"]` queremos guardar los dos.

Porque si sólo guardamos `["domingo", "faustino", "sarmiento"]`, si la persona busca "faustino sarmiento" el puntaje va a ser menor que si gurdamos también ese redirect. Entonces mejor guardarlo.

Lo que el código evita ahí es guardar  `["sarmiento", "faustino"]`, por ejemplo.

2021-01-11 22:32 UTC, marian-vignau commented on src/armado/cdpindex.py
> +                    if words in already_indexed_words:
Totalmente cierto. El tema es que por ejemplo el redirect "madres" que apunta a "Madres de Plaza de Mayo" desaparecería, haciendo que poner sólo "madres" no traiga éste como primer resultado.

2021-01-11 22:40 UTC, facundobatista commented on src/armado/cdpindex.py
> +                    if words in already_indexed_words:
Falso. Agregué un test para mostrarlo.

2021-01-15 23:28 UTC, marian-vignau approved these changes

2021-01-16 18:17 UTC, fzuccolo approved these changes
Quedó bárbaro!
Esto se puede sacar, ya no se usa:
https://github.com/PyAr/CDPedia/blob/8fd5a64850b3a9c443feb8c101e71fca60a37390/src/armado/cdpindex.py#L34-L35

2021-01-17 12:46 UTC, merged