Sqliteidx use indexentry struct
PyAr/CDPedia pull request #353
Opened 2021-01-14 21:04 UTC by marian-vignau

This document the API, a first step to a more flexible approach, which will store and resolve redirects inside the index.

2021-01-18 20:59 UTC, facundobatista requested changes
Algunos detalles, la mayoría menores. Charlemos si querés sobre la clase en sí. Gracias!!!

2021-01-18 20:59 UTC, facundobatista commented on src/armado/sqlite_index.py
> +        idx_entry = Indexentry(*row)
Hacerlo así es muy error prone, cambia algo en algún lado y empezamos a cargar el IndexEntry con fruta, mejor ser explícitos pasando algo como `foobar=row[0], ...`

2021-01-18 20:59 UTC, facundobatista commented on src/armado/sqlite_index.py
> +                idx_entry = tuple(idx_entry)
Lo mismo acá a nivel de "hacer explícita la traducción", armaría la tupla especificando cuales campos van.

Idea sin revisar demasiado: Y si pasás el `idx_entry` directamente al `docs_table.append`?

2021-01-18 20:59 UTC, facundobatista commented on utilities/search_index.py
> +    for nro, result in enumerate(result):
No uses el mismo nombre para el contenedor y para sus items...

2021-01-21 20:14 UTC, facundobatista requested changes
Algunas cositas quedaron de antes. Y agregué nuevas notas. Charlemos sobre los tests.

gracias!!

2021-01-21 20:14 UTC, facundobatista commented on tests/test_index.py
> +        docs = [n.strip().split("/") + [0] for n in data.split(";")]
¿por qué se le agrega el `[0]` acá?

2021-01-21 20:14 UTC, facundobatista commented on tests/test_index.py
> +        bbd/0
Charlemos sobre estos cambios, parecen muy tirados de los pelos...

2021-01-22 18:23 UTC, marian-vignau commented on tests/test_index.py
> +    docs = [(n[0], int(n[1])) for n in docs]
Antes, era una tupla, ahora es un objeto con varios atributos (__slots__).
Cuando era una tupla, seleccionaba los datos que quería de cada entrada del índice con slices.
Ahora, en cambio, agrego los scores. Es decir, compara con los scores que se devuelven también.

2021-01-22 18:36 UTC, marian-vignau commented on src/armado/cdpindex.py
> +                            rtype=2)
rtype=IndexEntry.TYPE_REDIRECT)

2021-01-22 18:38 UTC, marian-vignau commented on src/armado/cdpindex.py
> +                            score=ptje,
score se usa para el page_rank que viene del preprocesador. 
ptje es un número "normalizado" desde este. Lo que podría tener sentido, es guardar este dato sin normalizarlo para nada, no veo necesidad de pulirlo o mejorarlo

2021-01-22 18:41 UTC, marian-vignau commented on tests/test_cdpindex.py
> +    entries = []
quedó de la depuración se me pasó después

2021-01-22 18:47 UTC, marian-vignau commented on tests/test_index.py
> +        docs = [n.strip().split("/") + [0] for n in data.split(";")]
Para las últimas fixtures, las que testean por palabra parcial. Esto hace que sean más cortas de ingresar, ya que el score tiene un valor por defecto, el 0.

2021-01-22 18:55 UTC, marian-vignau commented on tests/test_cdpindex.py
> +    assert {e[2].rtype for e in entries[1:]} == {2}
El tema es que esto testea solo `cdpindex`, y mockea a la clase de Index, sea del tipo que sea. 
Por lo tanto, si no voy a hacer depender este test de nada del index, tengo que generar un falso `IndexEntry`, con por lo menos las constantes correspondientes cargadas.

2021-01-22 18:56 UTC, marian-vignau commented on tests/test_cdpindex.py
> +    assert entry.rtype in [0, 1]
El tema es que esto testea solo cdpindex, y mockea a la clase de Index, sea del tipo que sea.
Por lo tanto, si no voy a hacer depender este test de nada del index, tengo que generar un falso IndexEntry, con por lo menos las constantes correspondientes cargadas.

2021-01-29 11:22 UTC, facundobatista requested changes
Buen laburo!! Ahí agregué dos detalles, ya nos estamos acercando :)

2021-02-03 13:31 UTC, facundobatista approved these changes
Bien ahí! Rocanrol!!!

2021-02-03 13:31 UTC, merged