Sqliteidx tests improved
PyAr/CDPedia pull request #359
Opened 2021-02-03 15:06 UTC by marian-vignau

Everything is a lot more clean and easier.

2021-02-04 13:55 UTC, facundobatista requested changes
Ahí anoté unos detalles para simplificar la primera parte, vamos por buen camino! Gracias!

2021-02-04 13:55 UTC, facundobatista commented on tests/test_index.py
> +def IE(title):
Es una función, no uses mayúsculas. Estaría bueno que exprese que te da un IndexEntry. `get_indexentry` es claro, pero muy largo para todo lo que lo usás después. Qué te parece `get_ie`?

2021-02-04 13:55 UTC, facundobatista commented on tests/test_index.py
> +                      link=title.strip(),
Estos `.strip` no son necesarios, cierto?

2021-02-04 13:55 UTC, facundobatista commented on tests/test_index.py
> +def IE(title):
Y agregale un docstring.

2021-02-04 13:55 UTC, facundobatista commented on tests/test_index.py
> +def info(titles, function):
Mejorá también este nombre. ¿Qué hace la función? Y agregale un docstring.

2021-02-04 13:55 UTC, facundobatista commented on tests/test_index.py
> +def info(titles, function):
Me equivoco, o siempre que llamás a esta función, en "function" le pasás lo mismo? Para qué es "dinámico" eso?

2021-02-04 13:55 UTC, facundobatista commented on tests/test_index.py
> +def create_index(request, tmpdir):
Genial!

2021-02-05 21:14 UTC, marian-vignau commented on tests/test_index.py
> +                      link=title.strip(),
Si, porque en uno de los test uso un string de múltiples lineas, y en ese caso quedan espacios que luego generan errores.

2021-02-05 21:15 UTC, marian-vignau commented on tests/test_index.py
> +def info(titles, function):
Porque voy a tener que cambiar los tests cuando el sistema de redirects funcione, ya que las index_entries van a ser diferentes en este caso.

2021-02-09 12:13 UTC, facundobatista approved these changes
Buenísimo, gracias!!

2021-02-09 12:14 UTC, merged