Save pooled_exec func progress
PyAr/CDPedia pull request #361
Opened 2021-02-06 14:02 UTC by NicolasSandoval

close #343

2021-02-17 18:36 UTC, facundobatista commented
Esto habíamos hablado de cambiar la estructura general, sin guardar estado.

2021-03-22 14:22 UTC, facundobatista requested changes
Gran laburo! Ya casi estamos ahí, anoté unos detalles...

2021-03-22 14:22 UTC, facundobatista commented on src/scraping/css.py
> +        del items[:]
Acá arrancá una lista nueva y ya... `items = []`

2021-03-22 14:22 UTC, facundobatista commented on src/scraping/scraper.py
> +    data_urls.fh.close()
Este `.close()` no lo estás haciendo arriba ya?

2021-03-22 14:22 UTC, facundobatista commented on src/scraping/scraper.py
> +    r'(.+)\s*<div class="printfooter">')
¿De dónde viene este cambio?

2021-03-22 14:22 UTC, facundobatista commented on src/utiles.py
> +        board.ok = previous_count
Yo haría este logueo *siempre* (no sólo si previous_count).

Por otro lado, el `previous_count` se lo tenés que pasar a `_StatusBoard` y que esa clase "haga lo correcto", no toquetearle los atributos desde afuera...

2021-03-22 15:26 UTC, NicolasSandoval commented on src/scraping/css.py
> +        del items[:]
ok!

2021-03-22 15:27 UTC, NicolasSandoval commented on src/scraping/scraper.py
> +    data_urls.fh.close()
Si es correcto, removiendo.

2021-03-22 15:29 UTC, NicolasSandoval commented on src/scraping/scraper.py
> +    r'(.+)\s*<div class="printfooter">')
Me quedo de #367 para el test , lo saco y lo agregamos con github.

2021-03-22 15:30 UTC, NicolasSandoval commented on src/utiles.py
> +        board.ok = previous_count
Si mejor!

2021-03-22 15:42 UTC, NicolasSandoval commented
Cambios agregados, Gracias!

2021-03-23 00:05 UTC, facundobatista approved these changes
Buenísimo!!!!!!!!

2021-03-23 00:08 UTC, merged