Improve image processing logs
PyAr/CDPedia pull request #370
Opened 2021-03-12 23:34 UTC by NicolasSandoval

Some changes in logs:

```python3
2021-03-12 19:58:18,355  generar              INFO     Extracted 0 images, need to download 8008
2021-03-12 19:58:18,355  generar              INFO     Recalculating the reduction percentages.
2021-03-12 19:58:18,411  images.calculate     INFO     Add images: 20% - 1581 total | Scales: 395 at 100% - 395 at 75% - 791 at 50%
2021-03-12 19:58:18,414  images.calculate     INFO     Add 89 at 100% SVG images required - Total images to add: 1670
2021-03-12 19:58:18,416  generar              INFO     Downloading the images from the internet
2021-03-12 20:05:31,286  src.utiles           INFO     Scraping done! Total=1670  ok=1670  bad=0
2021-03-12 20:05:31,289  generar              INFO     Reducing the downloaded images
2021-03-12 20:05:32,073  images.scale         INFO     Resize done! | Final scales: 990 at 100% - 259 at 75% - 421 at 50%
2021-03-12 20:05:32,074  generar              INFO     Embedding selected images
2021-03-12 20:05:32,860  generar              INFO     Putting the reduced images into blocks
2021-03-12 20:05:33,078  generar              INFO     Got 8 blocks with 1581 images
2021-03-12 20:05:33,078  generar              INFO     Generating the index

```

2021-03-12 23:37 UTC, NicolasSandoval commented
Close #369

2021-03-18 03:09 UTC, NicolasSandoval commented
Add:
```python3
2021-03-17 23:26:50,264  images.scale         INFO     Formats and quantities -> svg: 89 - png: 565 - jpg: 1006 - gif: 14
```

2021-03-19 04:01 UTC, NicolasSandoval commented
Change:
```python3
2021-03-19 00:37:24,312  images.scale         INFO     Formats and quantities: svg=89 jpg=1006 png=564 gif=14
```

2021-03-23 18:11 UTC, facundobatista requested changes
Cambios que charlamos.

2021-03-23 18:11 UTC, facundobatista commented on src/images/calculate.py
> +        self.limit -= 1
```
def get_scales(self):
...     idx = 0
...     for quant, scale in scale_values:
...         for _ in range(quant):
...              yield (idx, scale)
...              idx += 1
```

2021-03-23 18:11 UTC, facundobatista commented on src/images/calculate.py
> +        logger.info("Add images: %i%% - %i total | Scales: %i at %i%% - %i at %i%% - %i at %i%%",
Hacerlo automáticamente y no depender de tener 3 escalas.

2021-03-23 18:11 UTC, facundobatista commented on src/images/calculate.py
> +        reduction = config.imageconf['image_reduction'][:-1]
Hay que validar!!! `assert sum(config.imageconf['image_reduction']) == 100`

Lo que no se es si conviene validarlo acá O ANTES. Fijarse cuando se carga la configuración. Revisá en `cdpetron.py` O (más posiblemente) en `cdpedia.py`.

El punto es. *donde* se cargue imageconf de disco, hay que validar esto.

2021-03-23 18:13 UTC, facundobatista requested changes

2021-03-23 18:13 UTC, facundobatista commented on src/images/calculate.py
>          info = (str(int(scale)), dskurl, weburl)
Acá no hace falta el `int()`

2021-03-24 00:29 UTC, NicolasSandoval commented on src/images/scale.py
> +    logger.info("Resize done! | Final scales: %(100)i at 100%% - %(75)i at 75%% - %(50)i at 50%%",
ok!

2021-03-24 00:29 UTC, NicolasSandoval commented on src/images/calculate.py
> +    logger.info("Add %i at 100%% SVG images required - Total images to add: %i",
ok!

2021-03-24 00:30 UTC, NicolasSandoval commented on src/images/calculate.py
> +        scale = scaler()
done!

2021-03-24 00:31 UTC, NicolasSandoval commented on src/images/calculate.py
> +        self.gen_pairs = iter(vals)
Use directamente `self.scale_values`

2021-03-24 00:32 UTC, NicolasSandoval commented on src/images/calculate.py
> +        self.limit -= 1
Gran idea! Me gusto.

2021-03-24 00:32 UTC, NicolasSandoval commented on src/images/calculate.py
> +        logger.info("Add images: %i%% - %i total | Scales: %i at %i%% - %i at %i%% - %i at %i%%",
done!

2021-03-24 00:39 UTC, NicolasSandoval commented on src/images/calculate.py
> +        reduction = config.imageconf['image_reduction'][:-1]
Lo estamos validando ya en `config.py`.

https://github.com/PyAr/CDPedia/blob/110b6b5b2cf43d481d6435ae78ae11f3633d5145/config.py#L166-L168

2021-03-24 00:39 UTC, NicolasSandoval commented on src/images/calculate.py
>          info = (str(int(scale)), dskurl, weburl)
Done!

2021-03-24 19:00 UTC, facundobatista requested changes
Dos detalles más y estamos!!!

2021-03-24 19:00 UTC, facundobatista commented on src/images/calculate.py
> +    def get_items(self):
Ponele un docstring.

2021-03-24 19:00 UTC, facundobatista commented on src/images/calculate.py
> +        limit = 0
Este contador es un índice de las imágenes, lo podemos llamar `idx` o `pos` (por "position"). Pero `limit` no encaja.

2021-03-24 20:18 UTC, NicolasSandoval commented on src/images/calculate.py
> +    def get_items(self):
ok!

2021-03-24 20:19 UTC, NicolasSandoval commented on src/images/calculate.py
> +        limit = 0
cambiando por `idx`

2021-03-26 12:54 UTC, facundobatista approved these changes
Buenísimoooooo

2021-03-26 13:01 UTC, merged