Translate some code, comments and docstrings
PyAr/CDPedia pull request #382
Opened 2021-03-28 20:16 UTC by y-martinez

This PR partially Close: #184 

This PR adds:

- Translate some code, comments, and docstrings.

2021-03-30 21:35 UTC, facundobatista requested changes
Awesome, thanks for this work! I included some slight changes. Thanks again!

2021-03-30 21:35 UTC, facundobatista commented on utilities/buscarEnBloque.py
> +        print("Long item returned", len(info))
```suggestion
        print("Returned item length", len(info))
```

2021-03-30 21:35 UTC, facundobatista commented on utilities/makeLista.py
> +    whose directory is where is decompressed the wikipedia
```suggestion
    directorye where the wikipedia is decompressed
```

2021-03-30 21:35 UTC, facundobatista commented on utilities/verComprimido.py
> +    print("The header (%d bytes): %d files in total" % (c.header_size, len(c.header)))
```suggestion
    print("From the header (%d bytes): %d files in total" % (c.header_size, len(c.header)))
```

2021-03-30 21:35 UTC, facundobatista commented on utilities/verComprimido.py
> +        print("           optionally, can pass files to extract")
```suggestion
        print("           optionally, files to extract can be indicated")
```

2021-04-08 14:11 UTC, y-martinez commented
Hi @facundobatista I made the changes requested, could you review it  please :smiley:

2021-04-08 21:16 UTC, facundobatista requested changes
Great work!!! Thanks!! I added some details inline, thanks again!

2021-04-08 21:16 UTC, facundobatista commented on src/armado/to3dirs.py
> +    """Remove the 3 directories of the path"""
Finish the sentence with a `.`.

2021-04-08 21:16 UTC, facundobatista commented on src/generate.py
> +            # we prepare paths and verify that everything is ok
remove the "we" when starting these comments

2021-04-08 21:16 UTC, facundobatista commented on src/web/destacados.py
> +        """Return a destacado randomly... eventually"""
You have to remove the Spanish docstring.

2021-04-09 21:54 UTC, y-martinez commented on utilities/benchmarkIndice.py
> +    print("               cant words:", len(palabras))
In this case, a valid translation can be `numbers of words` or maybe `quantity of words` what do you think?

2021-04-09 22:05 UTC, y-martinez commented on utilities/buscarEnBloque.py
> +        help=u"search in images (search for articles by default)")
I have doubts about this, I think that a possible solution is to translate
> search in images (searches articles by default)

or maybe 

> searches in images (shows articles by default)

2021-04-12 21:27 UTC, facundobatista commented
> Hi @facundobatista I made the changes requested, could you review it please smiley

Let me know please when you can check those details I marked, thanks!

2021-04-12 22:20 UTC, y-martinez commented
> > Hi @facundobatista I made the changes requested, could you review it please smiley
> 
> Let me know please when you can check those details I marked, thanks!

Yes I did make the changes but I have a few doubts so I asked you two questions above, can you see them?

2021-05-05 22:22 UTC, facundobatista commented on utilities/benchmarkIndice.py
> +    print("               cant words:", len(palabras))
quantity of words

2021-05-05 22:24 UTC, facundobatista commented on utilities/buscarEnBloque.py
> +        help=u"search in images (search for articles by default)")
My comment is about the consistency between the help messages of the different parameters. Make them all "imperative".

2021-05-05 22:24 UTC, facundobatista commented
I answered the questions, but found that lot of details I marked are not fixed.

2021-05-07 21:47 UTC, y-martinez commented
> I answered the questions, but found that lot of details I marked are not fixed.

Ohh gosh I was stupid, I forgot that I stashed those changes, and I didn't commit them, I already made the changes

2021-05-15 14:13 UTC, facundobatista approved these changes
Great, thanks!

2021-05-15 14:13 UTC, merged